"""Add user_id and vault_pin_hash

Revision ID: 7e7e7b18952d
Revises: 
Create Date: 2026-03-01 10:07:31.997758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7e7b18952d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # List of tables to add user_id to
    tables = [
        'agent_approvals', 'agent_traces', 'env_variables', 'global_configs',
        'integration_tokens', 'llm_connections', 'scheduled_flows', 'templates',
        'usage_logs', 'vault_keys', 'workspace_metadata'
    ]
    
    # 1. Add Column user_id as nullable=True
    for table in tables:
        op.add_column(table, sa.Column('user_id', sa.String(), nullable=True))
        
    # Special: Add vault_pin_hash to global_configs
    op.add_column('global_configs', sa.Column('vault_pin_hash', sa.String(), nullable=True))

    # 2. Assign default user_id to all existing rows
    for table in tables:
        op.execute(f"UPDATE {table} SET user_id = 'default_user' WHERE user_id IS NULL")

    # 3. Alter column to nullable=False using batch_alter_table (for SQLite)
    with op.batch_alter_table('agent_approvals', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_agent_approvals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_agent_traces_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('env_variables', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_env_variables_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('global_configs', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_global_configs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('integration_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_integration_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('llm_connections', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_llm_connections_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('scheduled_flows', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_scheduled_flows_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_templates_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('vault_keys', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_vault_keys_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('workspace_metadata', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.String(), nullable=False)
        batch_op.create_index(batch_op.f('ix_workspace_metadata_user_id'), ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_metadata_user_id'), table_name='workspace_metadata')
    op.drop_column('workspace_metadata', 'user_id')
    op.drop_index(op.f('ix_vault_keys_user_id'), table_name='vault_keys')
    op.drop_column('vault_keys', 'user_id')
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_column('usage_logs', 'user_id')
    op.drop_index(op.f('ix_templates_user_id'), table_name='templates')
    op.drop_column('templates', 'user_id')
    op.drop_index(op.f('ix_scheduled_flows_user_id'), table_name='scheduled_flows')
    op.drop_column('scheduled_flows', 'user_id')
    op.drop_index(op.f('ix_llm_connections_user_id'), table_name='llm_connections')
    op.drop_column('llm_connections', 'user_id')
    op.drop_index(op.f('ix_integration_tokens_user_id'), table_name='integration_tokens')
    op.drop_column('integration_tokens', 'user_id')
    op.drop_index(op.f('ix_global_configs_user_id'), table_name='global_configs')
    op.drop_column('global_configs', 'vault_pin_hash')
    op.drop_column('global_configs', 'user_id')
    op.drop_index(op.f('ix_env_variables_user_id'), table_name='env_variables')
    op.drop_column('env_variables', 'user_id')
    op.drop_index(op.f('ix_agent_traces_user_id'), table_name='agent_traces')
    op.drop_column('agent_traces', 'user_id')
    op.drop_index(op.f('ix_agent_approvals_user_id'), table_name='agent_approvals')
    op.drop_column('agent_approvals', 'user_id')
    # ### end Alembic commands ###
